services:
  db:
    image: mysql:9.1.0
    env_file: .env.dev
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.dev
    environment:
      DOCKER_ENV: docker
      DATABASE_HOST: db
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9000:8000"
    volumes:
      - .:/app


volumes:
  db-data: