# Generated by Django 5.0.7 on 2024-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='legajo',
            field=models.CharField(max_length=255, unique=True, verbose_name='legajo'),
        ),
    ]
