# Generated by Django 5.0.7 on 2024-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_user_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(default=1, max_length=100, verbose_name='documento'),
            preserve_default=False,
        ),
    ]
