# Generated by Django 5.0.7 on 2024-08-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(max_length=100, null=True, verbose_name='documento'),
        ),
    ]
