# Generated by Django 5.0.7 on 2024-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticionesservidor',
            fields=[
                ('peticion', models.IntegerField(blank=True, db_column='PETICION', null=True)),
                ('idpetici_n', models.AutoField(db_column='IDPETICIÓN', primary_key=True, serialize=False)),
                ('idexterna', models.CharField(blank=True, db_column='IDEXTERNA', max_length=20)),
                ('estado', models.SmallIntegerField(blank=True, db_column='ESTADO', null=True)),
                ('statussalida', models.TextField(blank=True, db_column='STATUSSALIDA')),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
                ('parametro1', models.TextField(blank=True, db_column='PARAMETRO1')),
                ('parametro2', models.TextField(blank=True, db_column='PARAMETRO2')),
                ('parametro3', models.TextField(blank=True, db_column='PARAMETRO3')),
                ('instancia', models.CharField(blank=True, db_column='INSTANCIA', max_length=20)),
            ],
            options={
                'db_table': 'PeticionesServidor',
                'managed': False,
            },
        ),
    ]
