# Generated by Django 5.0.7 on 2024-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(default=2024)),
                ('cuatrimestre', models.IntegerField(choices=[(1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')])),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
            ],
        ),
    ]
