# Generated by Django 5.0.7 on 2024-09-02 00:48

import django.db.models.deletion
import estudiantes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('codCoor', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, validators=[estudiantes.validators.validar_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('compromiso_contenido', models.FileField(blank=True, null=True, upload_to='compromiso/')),
                ('importe_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_reducido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_completo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materias', models.ManyToManyField(related_name='alumnos', to='estudiantes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reemplazo', models.DateTimeField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCuota', models.IntegerField()),
                ('año', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moraPrimerVencimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPrimerVencimiento', models.DateField()),
                ('moraSegundoVencimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaSegundoVencimiento', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importePagado', models.FloatField(null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFirma', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inhabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=255)),
                ('fechaFirma', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_informado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago_informado', models.DateField()),
                ('monto_confirmado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago_confirmado', models.DateField(blank=True, null=True)),
                ('comprobante_de_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('forma_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Transferencia', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='estudiantes.alumno')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parametroscompromiso',
            constraint=models.UniqueConstraint(fields=('año', 'cuatrimestre'), name='unique_año_cuatrimestre'),
        ),
        migrations.AddField(
            model_name='firmacompromiso',
            name='parametros_compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso'),
        ),
        migrations.AlterUniqueTogether(
            name='firmacompromiso',
            unique_together={('alumno', 'parametros_compromiso')},
        ),
    ]
