# Generated by Django 5.0.7 on 2024-12-02 21:13

import django.db.models.deletion
import estudiantes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('codCoor', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, validators=[estudiantes.validators.validar_nombre])),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('compromiso_contenido', models.FileField(blank=True, null=True, upload_to='compromiso/')),
                ('importe_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_reducido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_completo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudBajaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProrroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analitico', models.FileField(upload_to='prorroga/')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pago_al_dia', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materias', models.ManyToManyField(related_name='alumnos', to='estudiantes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCuota', models.IntegerField()),
                ('año', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moraPrimerVencimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPrimerVencimiento', models.DateField()),
                ('moraSegundoVencimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaSegundoVencimiento', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importePagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importeInformado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaImporteInformado', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('informada', 'Informada'), ('vencida', 'Vencida')], default='Pendiente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFirma', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inhabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('mensaje_grupal', models.BooleanField(default=False, verbose_name='Mensaje grupal')),
                ('destinatario', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Leído por')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.IntegerField()),
                ('monto_confirmado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago_confirmado', models.DateField(blank=True, null=True)),
                ('comprobante_de_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('forma_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Transferencia', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='estudiantes.alumno')),
                ('cuotas', models.ManyToManyField(through='estudiantes.DetallePago', to='estudiantes.cuota')),
            ],
        ),
        migrations.AddField(
            model_name='detallepago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.pago'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='pagos',
            field=models.ManyToManyField(through='estudiantes.DetallePago', to='estudiantes.pago'),
        ),
        migrations.AddConstraint(
            model_name='parametroscompromiso',
            constraint=models.UniqueConstraint(fields=('año', 'cuatrimestre'), name='unique_año_cuatrimestre'),
        ),
        migrations.AddField(
            model_name='firmacompromiso',
            name='parametros_compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso'),
        ),
        migrations.AddField(
            model_name='respuestamensaje',
            name='mensaje_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='estudiantes.mensaje', verbose_name='Mensaje original'),
        ),
        migrations.AddField(
            model_name='respuestamensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.AddField(
            model_name='solicitudbajaprovisoria',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno'),
        ),
        migrations.AddField(
            model_name='solicitudbajaprovisoria',
            name='compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso'),
        ),
        migrations.AddField(
            model_name='solicitudprorroga',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno'),
        ),
        migrations.AddField(
            model_name='solicitudprorroga',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepago',
            unique_together={('pago', 'cuota')},
        ),
        migrations.AlterUniqueTogether(
            name='firmacompromiso',
            unique_together={('alumno', 'parametros_compromiso')},
        ),
    ]
