# Generated by Django 5.0.7 on 2024-08-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='idMateria',
            new_name='codigo_materia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='FirmaCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFirma', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
                ('parametros_compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso')),
            ],
        ),
        migrations.DeleteModel(
            name='CompromisoPago',
        ),
    ]
