# Generated by Django 5.0.7 on 2024-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
