# Generated by Django 5.0.7 on 2024-07-31 19:50

import estudiantes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=50, validators=[estudiantes.validators.validar_nombre]),
        ),
    ]
