# Generated by Django 5.0.7 on 2024-08-21 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('compromiso_contenido', models.FileField(blank=True, null=True, upload_to='compromiso/')),
                ('importe_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_reducido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_completo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='compromisopago',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compromisopago',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reemplazo', models.DateTimeField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parametroscompromiso',
            constraint=models.UniqueConstraint(fields=('año', 'cuatrimestre'), name='unique_año_cuatrimestre'),
        ),
        migrations.AddField(
            model_name='compromisopago',
            name='parametros_compromiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso'),
        ),
    ]
