# Generated by Django 5.0.7 on 2024-12-12 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ingreso',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametroscompromiso',
            name='fecha_limite_baja',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
