# Generated by Django 5.0.7 on 2024-09-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
