# Generated by Django 5.0.7 on 2024-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroscompromiso',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametroscompromiso',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='parametroscompromiso',
            constraint=models.UniqueConstraint(fields=('año', 'cuatrimestre'), name='unique_año_cuatrimestre'),
        ),
    ]
