# Generated by Django 5.0.7 on 2024-09-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pago_al_dia',
            field=models.BooleanField(default=True),
        ),
    ]
