# Generated by Django 5.0.7 on 2024-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_delete_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='importePagado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
