# Generated by Django 5.0.7 on 2024-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_cuota_pago_al_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='pago_al_dia',
        ),
        migrations.AddField(
            model_name='alumno',
            name='pago_al_dia',
            field=models.BooleanField(default=True),
        ),
    ]
