# Generated by Django 5.0.7 on 2024-08-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alumno_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='idMateria',
            new_name='codigo_materia',
        ),
    ]
