# Generated by Django 5.0.7 on 2024-08-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_alumno_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosCompromiso',
            fields=[
                ('año', models.IntegerField(primary_key=True, serialize=False)),
                ('cuatrimestre', models.IntegerField()),
                ('compromiso_contenido', models.FileField(blank=True, null=True, upload_to='compromiso/')),
                ('importe_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_reducido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_completo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pri_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_comp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_seg_venc_red', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='compromisopago',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='compromisopago',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno'),
        ),
        migrations.AddField(
            model_name='compromisopago',
            name='parametros_compromiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.parametroscompromiso'),
        ),
    ]
