# Generated by Django 5.0.7 on 2024-08-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_rename_idmateria_materia_codigo_materia_alumno_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firmacompromiso',
            unique_together={('alumno', 'parametros_compromiso')},
        ),
    ]
