# Generated by Django 5.0.7 on 2024-12-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alumno_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(blank=True, null=True, related_name='alumnos', to='estudiantes.materia'),
        ),
    ]
