# Generated by Django 5.0.7 on 2024-10-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_cuota_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProrroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analitico', models.FileField(upload_to='prorroga/')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.materia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solicitudprorroga',
            constraint=models.UniqueConstraint(fields=('alumno', 'materia'), name='unique_prorroga_por_materia'),
        ),
    ]
