# Generated by Django 5.0.7 on 2024-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_alumno_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='ingreso',
            field=models.IntegerField(default=2024),
        ),
    ]
