# Generated by Django 5.0.7 on 2024-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_solicitudprorroga_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitudprorroga',
            name='unique_prorroga_por_materia',
        ),
        migrations.AddField(
            model_name='solicitudprorroga',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudprorroga',
            name='fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
