# Generated by Django 5.0.7 on 2024-09-17 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.pago')),
            ],
            options={
                'unique_together': {('pago', 'cuota')},
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='pagos',
            field=models.ManyToManyField(through='estudiantes.DetallePago', to='estudiantes.pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.ManyToManyField(through='estudiantes.DetallePago', to='estudiantes.cuota'),
        ),
    ]
