# Generated by Django 5.0.7 on 2024-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_detallepago_cuota_pagos_pago_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_recibo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
