# Generated by Django 5.0.7 on 2024-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_alumno_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(related_name='alumnos', to='estudiantes.materia'),
        ),
    ]
