on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
    env:
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: 127.0.0.1  # La IP local del contenedor de MySQL
      DB_PORT: 3306
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      GMAIL_TUP: ${{ secrets.GMAIL_TUP }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |  
        # Crea y activa un entorno virtual
        python -m venv venv
        . venv/bin/activate
        
    
        pip install -r requirements.txt

    - name: Create logs directory
      run: mkdir -p logs
    
    - name: crear base de datos
      run: |
        # Activa el entorno virtual
        . venv/bin/activate
        
        # Ejecuta las migraciones
        python create_database.py
        
    - name: Run Migrations
      run: |
        # Activa el entorno virtual
        . venv/bin/activate
        
        # Ejecuta las migraciones
        python manage.py migrate

    - name: Run Tests
      run: |

        # Activa el entorno virtual para esta sesión
        . venv/bin/activate
        
        # Ejecuta los tests
        pytest -v

    - name: scanear SonarCloud 
      uses: SonarSource/sonarcloud-github-action@master
      env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
          
