name: CI Workflow

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:9.1.0  
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3307:3306
        options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=25s
            --health-timeout=5s
            --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        run: |
            docker build -t aloric/seminario:latest .
            docker push aloric/seminario:latest

      - name: Install docker-compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: Run docker-compose
        run: |
            docker-compose -f docker-compose.yml up -d

      - name: Stop and remove containers
        run: |
          docker-compose down
